runtime: nodejs16

service: default

env_variables:
    TZ: "Asia/Seoul"
#     PS: "PROD"

entrypoint: node ./build/server.js

instance_class: F1
automatic_scaling:
    max_concurrent_requests: 50
    target_cpu_utilization: 0.93
    target_throughput_utilization: 0.93
    min_instances: 1
    min_idle_instances: 1

vpc_access_connector:
    # name: "projects/moneysylove/locations/asia-northeast3/connectors/moneysylove-conn-prod" // project: moneysylove
    name: "projects/moneysylove-dev-378310/locations/asia-northeast3/connectors/moneysylove-dev-app-conn"

handlers:
    # - url: /(.*\.(svg|png|jpg|css|js|gif))$
    #   static_files: page_resource/front/\1
    #   upload: page_resource/front/assets/.*\.(svg|png|jpg|css|js|gif|ttf)$
    #   application_readable: true
    # - url: /front
    #   static_dir: page_resource/front
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
